import { ref } from 'vue'

export const books = ref([
  {
    id: 1,
    name: 'Human Interactions Strategist',
    author: 'Alfredo Metz',
    genre: 'Thể loại A',
    bookcode: 'ABC',
    year: 2020,
    quantity: 5,
    totalQuantity: 10,
    description:
      'hihihihihihhihowareyouimfinethankyouandyoufinethankshesolohosolylyimhandsomeimlateiloveyouyouloveiiyoulovenhauhahahahahahahaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    image: 'https://th.bing.com/th/id/OIP.M6h8BZebDGpg4TsXREC9owHaNM?rs=1&pid=ImgDetMain',
  },
  {
    id: 2,
    name: 'Central Marketing Specialist',
    author: 'Mildred Koepp',
    genre: 'Thể loại A',
    bookcode: 'ABC',
    year: 2021,
    quantity: 0,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://demoda.vn/wp-content/uploads/2022/12/anh-meo-ngao-dang-ngap-ngu.jpg',
  },
  {
    id: 3,
    name: 'District Applications Technician',
    author: 'Grace Hand',
    genre: 'Thể loại A',
    year: 2019,
    quantity: 3,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://i.pinimg.com/736x/e2/19/be/e219be12e828fd91b36fb5cfd47b0b30.jpg',
  },
  {
    id: 4,
    name: 'Sách D',
    author: 'Tác giả D',
    genre: 'Thể loại A',
    year: 2022,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img.loigiaihay.com/picture/share_img/2024/0117/img-5582.jpeg',
  },
  {
    id: 5,
    name: 'Sách E',
    author: 'Tác giả E',
    genre: 'Thể loại A',
    year: 2025,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1yoi23.img?w=768&h=434&m=6',
  },
  {
    id: 6,
    name: 'Sách A',
    author: 'Tác giả A',
    genre: 'Thể loại B',
    year: 2020,
    quantity: 5,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image:
      'https://khoinguonsangtao.vn/wp-content/uploads/2022/08/anh-meme-meo-buon-anh-quat-em-a.jpg',
  },
  {
    id: 7,
    name: 'Sách B',
    author: 'Tác giả B',
    genre: 'Thể loại B',
    year: 2021,
    quantity: 0,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: 8,
    name: 'Sách C',
    author: 'Tác giả C',
    genre: 'Thể loại B',
    year: 2019,
    quantity: 3,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: 9,
    name: 'Sách D',
    author: 'Tác giả D',
    genre: 'Thể loại B',
    year: 2022,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: 10,
    name: 'Sách E',
    author: 'Tác giả E',
    genre: 'Thể loại B',
    year: 2025,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://picsum.photos/200/300',
  },
  {
    id: 1,
    name: 'Sách A',
    author: 'Tác giả A',
    genre: 'Thể loại A',
    bookcode: 'ABC',
    year: 2020,
    quantity: 5,
    totalQuantity: 10,
    description:
      'hihihihihihhihowareyouimfinethankyouandyoufinethankshesolohosolylyimhandsomeimlateiloveyouyouloveiiyoulovenhauhahahahahahahaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    image: 'https://th.bing.com/th/id/OIP.M6h8BZebDGpg4TsXREC9owHaNM?rs=1&pid=ImgDetMain',
  },
  {
    id: 2,
    name: 'Sách B',
    author: 'Tác giả B',
    genre: 'Thể loại A',
    bookcode: 'ABC',
    year: 2021,
    quantity: 0,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://demoda.vn/wp-content/uploads/2022/12/anh-meo-ngao-dang-ngap-ngu.jpg',
  },
  {
    id: 3,
    name: 'Sách C',
    author: 'Tác giả C',
    genre: 'Thể loại A',
    year: 2019,
    quantity: 3,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://i.pinimg.com/736x/e2/19/be/e219be12e828fd91b36fb5cfd47b0b30.jpg',
  },
  {
    id: 4,
    name: 'Sách D',
    author: 'Tác giả D',
    genre: 'Thể loại A',
    year: 2022,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img.loigiaihay.com/picture/share_img/2024/0117/img-5582.jpeg',
  },
  {
    id: 5,
    name: 'Sách E',
    author: 'Tác giả E',
    genre: 'Thể loại A',
    year: 2025,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1yoi23.img?w=768&h=434&m=6',
  },
  {
    id: 6,
    name: 'Sách A',
    author: 'Tác giả A',
    genre: 'Thể loại B',
    year: 2020,
    quantity: 5,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image:
      'https://khoinguonsangtao.vn/wp-content/uploads/2022/08/anh-meme-meo-buon-anh-quat-em-a.jpg',
  },
  {
    id: 7,
    name: 'Sách B',
    author: 'Tác giả B',
    genre: 'Thể loại B',
    year: 2021,
    quantity: 0,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1yoi23.img?w=768&h=434&m=6',
  },
  {
    id: 8,
    name: 'Sách C',
    author: 'Tác giả C',
    genre: 'Thể loại B',
    year: 2019,
    quantity: 3,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://i.pinimg.com/736x/e2/19/be/e219be12e828fd91b36fb5cfd47b0b30.jpg',
  },
  {
    id: 9,
    name: 'Sách D',
    author: 'Tác giả D',
    genre: 'Thể loại B',
    year: 2022,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img.loigiaihay.com/picture/share_img/2024/0117/img-5582.jpeg',
  },
  {
    id: 10,
    name: 'Sách E',
    author: 'Tác giả E',
    genre: 'Thể loại B',
    year: 2025,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image:
      'https://marketplace.canva.com/EAD46HNrYBs/1/0/1003w/canva-an-%E1%BB%A7i-l%C3%A3ng-m%E1%BA%A1n-s%C3%A1ch-b%C3%ACa-naZIEWMJArU.jpg',
  },
  {
    id: 1,
    name: 'Sách A',
    author: 'Tác giả A',
    genre: 'Thể loại A',
    bookcode: 'ABC',
    year: 2020,
    quantity: 5,
    totalQuantity: 10,
    description:
      'hihihihihihhihowareyouimfinethankyouandyoufinethankshesolohosolylyimhandsomeimlateiloveyouyouloveiiyoulovenhauhahahahahahahaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    image: 'https://th.bing.com/th/id/OIP.M6h8BZebDGpg4TsXREC9owHaNM?rs=1&pid=ImgDetMain',
  },
  {
    id: 2,
    name: 'Sách B',
    author: 'Tác giả B',
    genre: 'Thể loại A',
    bookcode: 'ABC',
    year: 2021,
    quantity: 0,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://demoda.vn/wp-content/uploads/2022/12/anh-meo-ngao-dang-ngap-ngu.jpg',
  },
  {
    id: 3,
    name: 'Sách C',
    author: 'Tác giả C',
    genre: 'Thể loại A',
    year: 2019,
    quantity: 3,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://i.pinimg.com/736x/e2/19/be/e219be12e828fd91b36fb5cfd47b0b30.jpg',
  },
  {
    id: 4,
    name: 'Sách D',
    author: 'Tác giả D',
    genre: 'Thể loại A',
    year: 2022,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img.loigiaihay.com/picture/share_img/2024/0117/img-5582.jpeg',
  },
  {
    id: 5,
    name: 'Sách E',
    author: 'Tác giả E',
    genre: 'Thể loại A',
    year: 2025,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1yoi23.img?w=768&h=434&m=6',
  },
  {
    id: 6,
    name: 'Sách A',
    author: 'Tác giả A',
    genre: 'Thể loại B',
    year: 2020,
    quantity: 5,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image:
      'https://khoinguonsangtao.vn/wp-content/uploads/2022/08/anh-meme-meo-buon-anh-quat-em-a.jpg',
  },
  {
    id: 7,
    name: 'Sách B',
    author: 'Tác giả B',
    genre: 'Thể loại B',
    year: 2021,
    quantity: 0,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1yoi23.img?w=768&h=434&m=6',
  },
  {
    id: 8,
    name: 'Sách C',
    author: 'Tác giả C',
    genre: 'Thể loại B',
    year: 2019,
    quantity: 3,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://i.pinimg.com/736x/e2/19/be/e219be12e828fd91b36fb5cfd47b0b30.jpg',
  },
  {
    id: 9,
    name: 'Sách A',
    author: 'Tác giả D',
    genre: 'Thể loại B',
    year: 2022,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img.loigiaihay.com/picture/share_img/2024/0117/img-5582.jpeg',
  },
  {
    id: 10,
    name: 'Sách A',
    author: 'Tác giả E',
    genre: 'Thể loại B',
    year: 2025,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image:
      'https://marketplace.canva.com/EAD46HNrYBs/1/0/1003w/canva-an-%E1%BB%A7i-l%C3%A3ng-m%E1%BA%A1n-s%C3%A1ch-b%C3%ACa-naZIEWMJArU.jpg',
  },
  {
    id: 1,
    name: 'Sách A',
    author: 'Tác giả A',
    genre: 'Thể loại A',
    bookcode: 'ABC',
    year: 2020,
    quantity: 5,
    totalQuantity: 10,
    description:
      'hihihihihihhihowareyouimfinethankyouandyoufinethankshesolohosolylyimhandsomeimlateiloveyouyouloveiiyoulovenhauhahahahahahahaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    image: 'https://th.bing.com/th/id/OIP.M6h8BZebDGpg4TsXREC9owHaNM?rs=1&pid=ImgDetMain',
  },
  {
    id: 2,
    name: 'Sách A',
    author: 'Tác giả B',
    genre: 'Thể loại A',
    bookcode: 'ABC',
    year: 2021,
    quantity: 0,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://demoda.vn/wp-content/uploads/2022/12/anh-meo-ngao-dang-ngap-ngu.jpg',
  },
  {
    id: 3,
    name: 'Sách A',
    author: 'Tác giả C',
    genre: 'Thể loại A',
    year: 2019,
    quantity: 3,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://i.pinimg.com/736x/e2/19/be/e219be12e828fd91b36fb5cfd47b0b30.jpg',
  },
  {
    id: 4,
    name: 'Sách A',
    author: 'Tác giả D',
    genre: 'Thể loại A',
    year: 2022,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img.loigiaihay.com/picture/share_img/2024/0117/img-5582.jpeg',
  },
  {
    id: 5,
    name: 'Sách A',
    author: 'Tác giả E',
    genre: 'Thể loại A',
    year: 2025,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1yoi23.img?w=768&h=434&m=6',
  },
  {
    id: 6,
    name: 'Sách A',
    author: 'Tác giả A',
    genre: 'Thể loại B',
    year: 2020,
    quantity: 5,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image:
      'https://khoinguonsangtao.vn/wp-content/uploads/2022/08/anh-meme-meo-buon-anh-quat-em-a.jpg',
  },
  {
    id: 7,
    name: 'Sách A',
    author: 'Tác giả B',
    genre: 'Thể loại B',
    year: 2021,
    quantity: 0,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1yoi23.img?w=768&h=434&m=6',
  },
  {
    id: 8,
    name: 'Sách A',
    author: 'Tác giả C',
    genre: 'Thể loại B',
    year: 2019,
    quantity: 3,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://i.pinimg.com/736x/e2/19/be/e219be12e828fd91b36fb5cfd47b0b30.jpg',
  },
  {
    id: 9,
    name: 'Sách A',
    author: 'Tác giả D',
    genre: 'Thể loại B',
    year: 2022,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img.loigiaihay.com/picture/share_img/2024/0117/img-5582.jpeg',
  },
  {
    id: 10,
    name: 'Sách A',
    author: 'Tác giả E',
    genre: 'Thể loại B',
    year: 2025,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image:
      'https://marketplace.canva.com/EAD46HNrYBs/1/0/1003w/canva-an-%E1%BB%A7i-l%C3%A3ng-m%E1%BA%A1n-s%C3%A1ch-b%C3%ACa-naZIEWMJArU.jpg',
  },
  {
    id: 1,
    name: 'Sách A',
    author: 'Tác giả A',
    genre: 'Thể loại A',
    bookcode: 'ABC',
    year: 2020,
    quantity: 5,
    totalQuantity: 10,
    description:
      'hihihihihihhihowareyouimfinethankyouandyoufinethankshesolohosolylyimhandsomeimlateiloveyouyouloveiiyoulovenhauhahahahahahahaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    image: 'https://th.bing.com/th/id/OIP.M6h8BZebDGpg4TsXREC9owHaNM?rs=1&pid=ImgDetMain',
  },
  {
    id: 2,
    name: 'Sách A',
    author: 'Tác giả B',
    genre: 'Thể loại A',
    bookcode: 'ABC',
    year: 2021,
    quantity: 0,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://demoda.vn/wp-content/uploads/2022/12/anh-meo-ngao-dang-ngap-ngu.jpg',
  },
  {
    id: 3,
    name: 'Sách A',
    author: 'Tác giả C',
    genre: 'Thể loại A',
    year: 2019,
    quantity: 3,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://i.pinimg.com/736x/e2/19/be/e219be12e828fd91b36fb5cfd47b0b30.jpg',
  },
  {
    id: 4,
    name: 'Sách A',
    author: 'Tác giả D',
    genre: 'Thể loại A',
    year: 2022,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img.loigiaihay.com/picture/share_img/2024/0117/img-5582.jpeg',
  },
  {
    id: 5,
    name: 'Sách A',
    author: 'Tác giả E',
    genre: 'Thể loại A',
    year: 2025,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1yoi23.img?w=768&h=434&m=6',
  },
  {
    id: 6,
    name: 'Sách A',
    author: 'Tác giả A',
    genre: 'Thể loại B',
    year: 2020,
    quantity: 5,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image:
      'https://khoinguonsangtao.vn/wp-content/uploads/2022/08/anh-meme-meo-buon-anh-quat-em-a.jpg',
  },
  {
    id: 7,
    name: 'Sách A',
    author: 'Tác giả B',
    genre: 'Thể loại B',
    year: 2021,
    quantity: 0,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA1yoi23.img?w=768&h=434&m=6',
  },
  {
    id: 8,
    name: 'Sách A',
    author: 'Tác giả C',
    genre: 'Thể loại B',
    year: 2019,
    quantity: 3,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://i.pinimg.com/736x/e2/19/be/e219be12e828fd91b36fb5cfd47b0b30.jpg',
  },
  {
    id: 9,
    name: 'Sách A',
    author: 'Tác giả D',
    genre: 'Thể loại B',
    year: 2022,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image: 'https://img.loigiaihay.com/picture/share_img/2024/0117/img-5582.jpeg',
  },
  {
    id: 10,
    name: 'Sách A',
    author: 'Tác giả E',
    genre: 'Thể loại B',
    year: 2025,
    quantity: 10,
    totalQuantity: 10,
    description: 'hihihihihihhi',
    image:
      'https://marketplace.canva.com/EAD46HNrYBs/1/0/1003w/canva-an-%E1%BB%A7i-l%C3%A3ng-m%E1%BA%A1n-s%C3%A1ch-b%C3%ACa-naZIEWMJArU.jpg',
  },
])
